// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250815101308_AddUserRolesAndSeedData")]
    partial class AddUserRolesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 15, 10, 13, 7, 851, DateTimeKind.Utc).AddTicks(4873),
                            Name = "Laptop Pro",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 15, 10, 13, 7, 851, DateTimeKind.Utc).AddTicks(4876),
                            Name = "Wireless Mouse",
                            Price = 25.50m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 15, 10, 13, 7, 851, DateTimeKind.Utc).AddTicks(4878),
                            Name = "Mechanical Keyboard",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 15, 10, 13, 7, 851, DateTimeKind.Utc).AddTicks(4880),
                            Name = "4K Monitor",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 15, 10, 13, 7, 851, DateTimeKind.Utc).AddTicks(4881),
                            Name = "Webcam HD",
                            Price = 60.00m
                        });
                });

            modelBuilder.Entity("MyApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2b$11$N3VV3pY3eVD6ml.Eo.PRa.58wjNxyhgcB2f2e8YVWN5Ed18znzigu",
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
